# coding: utf-8

"""
    xCherry APIs

    This APIs between xCherry service and SDKs

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, ClassVar, Dict, List, Optional
from pydantic import BaseModel, StrictStr
from pydantic import Field
from xcherryapi.models.state_failure_recovery_policy import StateFailureRecoveryPolicy
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class StateFailureRecoveryOptions(BaseModel):
    """
    StateFailureRecoveryOptions
    """ # noqa: E501
    policy: StateFailureRecoveryPolicy
    state_failure_proceed_state_id: Optional[StrictStr] = Field(default=None, alias="stateFailureProceedStateId")
    state_failure_proceed_state_config: Optional[AsyncStateConfig] = Field(default=None, alias="stateFailureProceedStateConfig")
    __properties: ClassVar[List[str]] = ["policy", "stateFailureProceedStateId", "stateFailureProceedStateConfig"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of StateFailureRecoveryOptions from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of state_failure_proceed_state_config
        if self.state_failure_proceed_state_config:
            _dict['stateFailureProceedStateConfig'] = self.state_failure_proceed_state_config.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of StateFailureRecoveryOptions from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "policy": obj.get("policy"),
            "stateFailureProceedStateId": obj.get("stateFailureProceedStateId"),
            "stateFailureProceedStateConfig": AsyncStateConfig.from_dict(obj.get("stateFailureProceedStateConfig")) if obj.get("stateFailureProceedStateConfig") is not None else None
        })
        return _obj

from xcherryapi.models.async_state_config import AsyncStateConfig
# TODO: Rewrite to not use raise_errors
StateFailureRecoveryOptions.model_rebuild(raise_errors=False)

