/*
XDB APIs

This APIs between xdb service and SDKs

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package xdbapi

import (
	"encoding/json"
)

// checks if the LoadGlobalAttributeResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LoadGlobalAttributeResponse{}

// LoadGlobalAttributeResponse the response for loading global attributes
type LoadGlobalAttributeResponse struct {
	TableResponses []TableReadResponse `json:"tableResponses,omitempty"`
}

// NewLoadGlobalAttributeResponse instantiates a new LoadGlobalAttributeResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLoadGlobalAttributeResponse() *LoadGlobalAttributeResponse {
	this := LoadGlobalAttributeResponse{}
	return &this
}

// NewLoadGlobalAttributeResponseWithDefaults instantiates a new LoadGlobalAttributeResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLoadGlobalAttributeResponseWithDefaults() *LoadGlobalAttributeResponse {
	this := LoadGlobalAttributeResponse{}
	return &this
}

// GetTableResponses returns the TableResponses field value if set, zero value otherwise.
func (o *LoadGlobalAttributeResponse) GetTableResponses() []TableReadResponse {
	if o == nil || IsNil(o.TableResponses) {
		var ret []TableReadResponse
		return ret
	}
	return o.TableResponses
}

// GetTableResponsesOk returns a tuple with the TableResponses field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LoadGlobalAttributeResponse) GetTableResponsesOk() ([]TableReadResponse, bool) {
	if o == nil || IsNil(o.TableResponses) {
		return nil, false
	}
	return o.TableResponses, true
}

// HasTableResponses returns a boolean if a field has been set.
func (o *LoadGlobalAttributeResponse) HasTableResponses() bool {
	if o != nil && !IsNil(o.TableResponses) {
		return true
	}

	return false
}

// SetTableResponses gets a reference to the given []TableReadResponse and assigns it to the TableResponses field.
func (o *LoadGlobalAttributeResponse) SetTableResponses(v []TableReadResponse) {
	o.TableResponses = v
}

func (o LoadGlobalAttributeResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LoadGlobalAttributeResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TableResponses) {
		toSerialize["tableResponses"] = o.TableResponses
	}
	return toSerialize, nil
}

type NullableLoadGlobalAttributeResponse struct {
	value *LoadGlobalAttributeResponse
	isSet bool
}

func (v NullableLoadGlobalAttributeResponse) Get() *LoadGlobalAttributeResponse {
	return v.value
}

func (v *NullableLoadGlobalAttributeResponse) Set(val *LoadGlobalAttributeResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableLoadGlobalAttributeResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableLoadGlobalAttributeResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLoadGlobalAttributeResponse(val *LoadGlobalAttributeResponse) *NullableLoadGlobalAttributeResponse {
	return &NullableLoadGlobalAttributeResponse{value: val, isSet: true}
}

func (v NullableLoadGlobalAttributeResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLoadGlobalAttributeResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
