/*
XDB APIs

This APIs between xdb service and SDKs

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package xdbapi

import (
	"encoding/json"
)

// checks if the ProcessRpcRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProcessRpcRequest{}

// ProcessRpcRequest the input of the rpc API
type ProcessRpcRequest struct {
	Context                Context                      `json:"context"`
	ProcessType            string                       `json:"processType"`
	RpcName                string                       `json:"rpcName"`
	Input                  *EncodedObject               `json:"input,omitempty"`
	LoadedGlobalAttributes *LoadGlobalAttributeResponse `json:"loadedGlobalAttributes,omitempty"`
}

// NewProcessRpcRequest instantiates a new ProcessRpcRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProcessRpcRequest(context Context, processType string, rpcName string) *ProcessRpcRequest {
	this := ProcessRpcRequest{}
	this.Context = context
	this.ProcessType = processType
	this.RpcName = rpcName
	return &this
}

// NewProcessRpcRequestWithDefaults instantiates a new ProcessRpcRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProcessRpcRequestWithDefaults() *ProcessRpcRequest {
	this := ProcessRpcRequest{}
	return &this
}

// GetContext returns the Context field value
func (o *ProcessRpcRequest) GetContext() Context {
	if o == nil {
		var ret Context
		return ret
	}

	return o.Context
}

// GetContextOk returns a tuple with the Context field value
// and a boolean to check if the value has been set.
func (o *ProcessRpcRequest) GetContextOk() (*Context, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Context, true
}

// SetContext sets field value
func (o *ProcessRpcRequest) SetContext(v Context) {
	o.Context = v
}

// GetProcessType returns the ProcessType field value
func (o *ProcessRpcRequest) GetProcessType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProcessType
}

// GetProcessTypeOk returns a tuple with the ProcessType field value
// and a boolean to check if the value has been set.
func (o *ProcessRpcRequest) GetProcessTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProcessType, true
}

// SetProcessType sets field value
func (o *ProcessRpcRequest) SetProcessType(v string) {
	o.ProcessType = v
}

// GetRpcName returns the RpcName field value
func (o *ProcessRpcRequest) GetRpcName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RpcName
}

// GetRpcNameOk returns a tuple with the RpcName field value
// and a boolean to check if the value has been set.
func (o *ProcessRpcRequest) GetRpcNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RpcName, true
}

// SetRpcName sets field value
func (o *ProcessRpcRequest) SetRpcName(v string) {
	o.RpcName = v
}

// GetInput returns the Input field value if set, zero value otherwise.
func (o *ProcessRpcRequest) GetInput() EncodedObject {
	if o == nil || IsNil(o.Input) {
		var ret EncodedObject
		return ret
	}
	return *o.Input
}

// GetInputOk returns a tuple with the Input field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProcessRpcRequest) GetInputOk() (*EncodedObject, bool) {
	if o == nil || IsNil(o.Input) {
		return nil, false
	}
	return o.Input, true
}

// HasInput returns a boolean if a field has been set.
func (o *ProcessRpcRequest) HasInput() bool {
	if o != nil && !IsNil(o.Input) {
		return true
	}

	return false
}

// SetInput gets a reference to the given EncodedObject and assigns it to the Input field.
func (o *ProcessRpcRequest) SetInput(v EncodedObject) {
	o.Input = &v
}

// GetLoadedGlobalAttributes returns the LoadedGlobalAttributes field value if set, zero value otherwise.
func (o *ProcessRpcRequest) GetLoadedGlobalAttributes() LoadGlobalAttributeResponse {
	if o == nil || IsNil(o.LoadedGlobalAttributes) {
		var ret LoadGlobalAttributeResponse
		return ret
	}
	return *o.LoadedGlobalAttributes
}

// GetLoadedGlobalAttributesOk returns a tuple with the LoadedGlobalAttributes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProcessRpcRequest) GetLoadedGlobalAttributesOk() (*LoadGlobalAttributeResponse, bool) {
	if o == nil || IsNil(o.LoadedGlobalAttributes) {
		return nil, false
	}
	return o.LoadedGlobalAttributes, true
}

// HasLoadedGlobalAttributes returns a boolean if a field has been set.
func (o *ProcessRpcRequest) HasLoadedGlobalAttributes() bool {
	if o != nil && !IsNil(o.LoadedGlobalAttributes) {
		return true
	}

	return false
}

// SetLoadedGlobalAttributes gets a reference to the given LoadGlobalAttributeResponse and assigns it to the LoadedGlobalAttributes field.
func (o *ProcessRpcRequest) SetLoadedGlobalAttributes(v LoadGlobalAttributeResponse) {
	o.LoadedGlobalAttributes = &v
}

func (o ProcessRpcRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProcessRpcRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["context"] = o.Context
	toSerialize["processType"] = o.ProcessType
	toSerialize["rpcName"] = o.RpcName
	if !IsNil(o.Input) {
		toSerialize["input"] = o.Input
	}
	if !IsNil(o.LoadedGlobalAttributes) {
		toSerialize["loadedGlobalAttributes"] = o.LoadedGlobalAttributes
	}
	return toSerialize, nil
}

type NullableProcessRpcRequest struct {
	value *ProcessRpcRequest
	isSet bool
}

func (v NullableProcessRpcRequest) Get() *ProcessRpcRequest {
	return v.value
}

func (v *NullableProcessRpcRequest) Set(val *ProcessRpcRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableProcessRpcRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableProcessRpcRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProcessRpcRequest(val *ProcessRpcRequest) *NullableProcessRpcRequest {
	return &NullableProcessRpcRequest{value: val, isSet: true}
}

func (v NullableProcessRpcRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProcessRpcRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
