/*
XDB APIs

This APIs between xdb service and SDKs

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package xdbapi

import (
	"encoding/json"
)

// checks if the ProcessExecutionRpcResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProcessExecutionRpcResponse{}

// ProcessExecutionRpcResponse the response for executing a RPC method of a process execution
type ProcessExecutionRpcResponse struct {
	Output *EncodedObject `json:"output,omitempty"`
}

// NewProcessExecutionRpcResponse instantiates a new ProcessExecutionRpcResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProcessExecutionRpcResponse() *ProcessExecutionRpcResponse {
	this := ProcessExecutionRpcResponse{}
	return &this
}

// NewProcessExecutionRpcResponseWithDefaults instantiates a new ProcessExecutionRpcResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProcessExecutionRpcResponseWithDefaults() *ProcessExecutionRpcResponse {
	this := ProcessExecutionRpcResponse{}
	return &this
}

// GetOutput returns the Output field value if set, zero value otherwise.
func (o *ProcessExecutionRpcResponse) GetOutput() EncodedObject {
	if o == nil || IsNil(o.Output) {
		var ret EncodedObject
		return ret
	}
	return *o.Output
}

// GetOutputOk returns a tuple with the Output field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProcessExecutionRpcResponse) GetOutputOk() (*EncodedObject, bool) {
	if o == nil || IsNil(o.Output) {
		return nil, false
	}
	return o.Output, true
}

// HasOutput returns a boolean if a field has been set.
func (o *ProcessExecutionRpcResponse) HasOutput() bool {
	if o != nil && !IsNil(o.Output) {
		return true
	}

	return false
}

// SetOutput gets a reference to the given EncodedObject and assigns it to the Output field.
func (o *ProcessExecutionRpcResponse) SetOutput(v EncodedObject) {
	o.Output = &v
}

func (o ProcessExecutionRpcResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProcessExecutionRpcResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Output) {
		toSerialize["output"] = o.Output
	}
	return toSerialize, nil
}

type NullableProcessExecutionRpcResponse struct {
	value *ProcessExecutionRpcResponse
	isSet bool
}

func (v NullableProcessExecutionRpcResponse) Get() *ProcessExecutionRpcResponse {
	return v.value
}

func (v *NullableProcessExecutionRpcResponse) Set(val *ProcessExecutionRpcResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableProcessExecutionRpcResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableProcessExecutionRpcResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProcessExecutionRpcResponse(val *ProcessExecutionRpcResponse) *NullableProcessExecutionRpcResponse {
	return &NullableProcessExecutionRpcResponse{value: val, isSet: true}
}

func (v NullableProcessExecutionRpcResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProcessExecutionRpcResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
