# coding: utf-8

"""
    xCherry APIs

    This APIs between xCherry service and SDKs

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from xcherryapi.models.process_status import ProcessStatus

class TestProcessStatus(unittest.TestCase):
    """ProcessStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProcessStatus(self):
        """Test ProcessStatus"""
        # inst = ProcessStatus()

if __name__ == '__main__':
    unittest.main()
