# coding: utf-8

"""
    xCherry APIs

    This APIs between xCherry service and SDKs

    The version of the OpenAPI document: 0.0.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from xcherryapi.models.context import Context

class TestContext(unittest.TestCase):
    """Context unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Context:
        """Test Context
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Context`
        """
        model = Context()
        if include_optional:
            return Context(
                process_id = '',
                process_execution_id = '',
                process_started_timestamp = 56,
                state_execution_id = '',
                first_attempt_timestamp = 56,
                attempt = 56,
                recover_from_state_execution_id = '',
                recover_from_api = 'WAIT_UNTIL_API'
            )
        else:
            return Context(
                process_id = '',
                process_execution_id = '',
                process_started_timestamp = 56,
        )
        """

    def testContext(self):
        """Test Context"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
