# coding: utf-8

"""
    xCherry APIs

    This APIs between xCherry service and SDKs

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from xcherryapi.models.publish_to_local_queue_request import PublishToLocalQueueRequest

class TestPublishToLocalQueueRequest(unittest.TestCase):
    """PublishToLocalQueueRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PublishToLocalQueueRequest:
        """Test PublishToLocalQueueRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PublishToLocalQueueRequest`
        """
        model = PublishToLocalQueueRequest()
        if include_optional:
            return PublishToLocalQueueRequest(
                namespace = '',
                process_id = '',
                messages = [
                    xcherryapi.models.local_queue_message.LocalQueueMessage(
                        queue_name = '', 
                        dedup_id = '', 
                        payload = xcherryapi.models.encoded_object.EncodedObject(
                            encoding = '', 
                            data = '', ), )
                    ]
            )
        else:
            return PublishToLocalQueueRequest(
                namespace = '',
                process_id = '',
        )
        """

    def testPublishToLocalQueueRequest(self):
        """Test PublishToLocalQueueRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
