# coding: utf-8

"""
    xCherry APIs

    This APIs between xCherry service and SDKs

    The version of the OpenAPI document: 0.0.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from xcherryapi.models.command_status import CommandStatus

class TestCommandStatus(unittest.TestCase):
    """CommandStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCommandStatus(self):
        """Test CommandStatus"""
        # inst = CommandStatus()

if __name__ == '__main__':
    unittest.main()
