# coding: utf-8

"""
    xCherry APIs

    This APIs between xCherry service and SDKs

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from xcherryapi.models.app_database_table_read_request import AppDatabaseTableReadRequest

class TestAppDatabaseTableReadRequest(unittest.TestCase):
    """AppDatabaseTableReadRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AppDatabaseTableReadRequest:
        """Test AppDatabaseTableReadRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AppDatabaseTableReadRequest`
        """
        model = AppDatabaseTableReadRequest()
        if include_optional:
            return AppDatabaseTableReadRequest(
                table_name = '',
                lock_type = 'NO_LOCKING',
                columns = [
                    ''
                    ]
            )
        else:
            return AppDatabaseTableReadRequest(
        )
        """

    def testAppDatabaseTableReadRequest(self):
        """Test AppDatabaseTableReadRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
