# coding: utf-8

"""
    xCherry APIs

    This APIs between xCherry service and SDKs

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from xcherryapi.models.async_state_wait_until_request import AsyncStateWaitUntilRequest

class TestAsyncStateWaitUntilRequest(unittest.TestCase):
    """AsyncStateWaitUntilRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AsyncStateWaitUntilRequest:
        """Test AsyncStateWaitUntilRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AsyncStateWaitUntilRequest`
        """
        model = AsyncStateWaitUntilRequest()
        if include_optional:
            return AsyncStateWaitUntilRequest(
                context = xcherryapi.models.context.Context(
                    process_id = '', 
                    process_execution_id = '', 
                    process_started_timestamp = 56, 
                    state_execution_id = '', 
                    first_attempt_timestamp = 56, 
                    attempt = 56, 
                    recover_from_state_execution_id = '', 
                    recover_from_api = 'WAIT_UNTIL_API', ),
                process_type = '',
                state_id = '',
                state_input = xcherryapi.models.encoded_object.EncodedObject(
                    encoding = '', 
                    data = '', )
            )
        else:
            return AsyncStateWaitUntilRequest(
                context = xcherryapi.models.context.Context(
                    process_id = '', 
                    process_execution_id = '', 
                    process_started_timestamp = 56, 
                    state_execution_id = '', 
                    first_attempt_timestamp = 56, 
                    attempt = 56, 
                    recover_from_state_execution_id = '', 
                    recover_from_api = 'WAIT_UNTIL_API', ),
                process_type = '',
                state_id = '',
        )
        """

    def testAsyncStateWaitUntilRequest(self):
        """Test AsyncStateWaitUntilRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
