# coding: utf-8

"""
    xCherry APIs

    This APIs between xCherry service and SDKs

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from xcherryapi.models.app_database_write import AppDatabaseWrite

class TestAppDatabaseWrite(unittest.TestCase):
    """AppDatabaseWrite unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AppDatabaseWrite:
        """Test AppDatabaseWrite
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AppDatabaseWrite`
        """
        model = AppDatabaseWrite()
        if include_optional:
            return AppDatabaseWrite(
                tables = [
                    xcherryapi.models.app_database_table_write.AppDatabaseTableWrite(
                        table_name = '', 
                        rows = [
                            xcherryapi.models.app_database_row_write.AppDatabaseRowWrite(
                                primary_key = [
                                    xcherryapi.models.app_database_column_value.AppDatabaseColumnValue(
                                        column = '', 
                                        query_value = '', )
                                    ], 
                                write_columns = [
                                    xcherryapi.models.app_database_column_value.AppDatabaseColumnValue(
                                        column = '', 
                                        query_value = '', )
                                    ], )
                            ], )
                    ]
            )
        else:
            return AppDatabaseWrite(
        )
        """

    def testAppDatabaseWrite(self):
        """Test AppDatabaseWrite"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
