# coding: utf-8

"""
    xCherry APIs

    This APIs between xCherry service and SDKs

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from xcherryapi.models.load_local_attributes_request import LoadLocalAttributesRequest

class TestLoadLocalAttributesRequest(unittest.TestCase):
    """LoadLocalAttributesRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LoadLocalAttributesRequest:
        """Test LoadLocalAttributesRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LoadLocalAttributesRequest`
        """
        model = LoadLocalAttributesRequest()
        if include_optional:
            return LoadLocalAttributesRequest(
                keys_to_load_no_lock = [
                    ''
                    ],
                keys_to_load_with_lock = [
                    ''
                    ],
                lock_type = 'NO_LOCKING'
            )
        else:
            return LoadLocalAttributesRequest(
        )
        """

    def testLoadLocalAttributesRequest(self):
        """Test LoadLocalAttributesRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
