# coding: utf-8

"""
    xCherry APIs

    This APIs between xCherry service and SDKs

    The version of the OpenAPI document: 0.0.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from xcherryapi.models.process_execution_wait_for_completion_request import ProcessExecutionWaitForCompletionRequest

class TestProcessExecutionWaitForCompletionRequest(unittest.TestCase):
    """ProcessExecutionWaitForCompletionRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProcessExecutionWaitForCompletionRequest:
        """Test ProcessExecutionWaitForCompletionRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProcessExecutionWaitForCompletionRequest`
        """
        model = ProcessExecutionWaitForCompletionRequest()
        if include_optional:
            return ProcessExecutionWaitForCompletionRequest(
                namespace = '',
                process_id = '',
                timeout_seconds = 56
            )
        else:
            return ProcessExecutionWaitForCompletionRequest(
                namespace = '',
                process_id = '',
        )
        """

    def testProcessExecutionWaitForCompletionRequest(self):
        """Test ProcessExecutionWaitForCompletionRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
