# coding: utf-8

"""
    xCherry APIs

    This APIs between xCherry service and SDKs

    The version of the OpenAPI document: 0.0.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from xcherryapi.models.signal_process_completion_request import SignalProcessCompletionRequest

class TestSignalProcessCompletionRequest(unittest.TestCase):
    """SignalProcessCompletionRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SignalProcessCompletionRequest:
        """Test SignalProcessCompletionRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SignalProcessCompletionRequest`
        """
        model = SignalProcessCompletionRequest()
        if include_optional:
            return SignalProcessCompletionRequest(
                shard_id = 56,
                process_execution_id = '',
                status = ''
            )
        else:
            return SignalProcessCompletionRequest(
                shard_id = 56,
                process_execution_id = '',
                status = '',
        )
        """

    def testSignalProcessCompletionRequest(self):
        """Test SignalProcessCompletionRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
