# coding: utf-8

"""
    xCherry APIs

    This APIs between xCherry service and SDKs

    The version of the OpenAPI document: 0.0.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from xcherryapi.models.process_id_filter import ProcessIdFilter

class TestProcessIdFilter(unittest.TestCase):
    """ProcessIdFilter unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProcessIdFilter:
        """Test ProcessIdFilter
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProcessIdFilter`
        """
        model = ProcessIdFilter()
        if include_optional:
            return ProcessIdFilter(
                process_id = ''
            )
        else:
            return ProcessIdFilter(
        )
        """

    def testProcessIdFilter(self):
        """Test ProcessIdFilter"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
