/*
xCherry APIs

This APIs between xCherry service and SDKs

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package xcapi

import (
	"encoding/json"
)

// checks if the ProcessExecutionStartResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProcessExecutionStartResponse{}

// ProcessExecutionStartResponse response of ProcessExecutionStartRequest
type ProcessExecutionStartResponse struct {
	// a UUID as the unique identifier of a process execution
	ProcessExecutionId string `json:"processExecutionId"`
}

// NewProcessExecutionStartResponse instantiates a new ProcessExecutionStartResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProcessExecutionStartResponse(processExecutionId string) *ProcessExecutionStartResponse {
	this := ProcessExecutionStartResponse{}
	this.ProcessExecutionId = processExecutionId
	return &this
}

// NewProcessExecutionStartResponseWithDefaults instantiates a new ProcessExecutionStartResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProcessExecutionStartResponseWithDefaults() *ProcessExecutionStartResponse {
	this := ProcessExecutionStartResponse{}
	return &this
}

// GetProcessExecutionId returns the ProcessExecutionId field value
func (o *ProcessExecutionStartResponse) GetProcessExecutionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProcessExecutionId
}

// GetProcessExecutionIdOk returns a tuple with the ProcessExecutionId field value
// and a boolean to check if the value has been set.
func (o *ProcessExecutionStartResponse) GetProcessExecutionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProcessExecutionId, true
}

// SetProcessExecutionId sets field value
func (o *ProcessExecutionStartResponse) SetProcessExecutionId(v string) {
	o.ProcessExecutionId = v
}

func (o ProcessExecutionStartResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProcessExecutionStartResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["processExecutionId"] = o.ProcessExecutionId
	return toSerialize, nil
}

type NullableProcessExecutionStartResponse struct {
	value *ProcessExecutionStartResponse
	isSet bool
}

func (v NullableProcessExecutionStartResponse) Get() *ProcessExecutionStartResponse {
	return v.value
}

func (v *NullableProcessExecutionStartResponse) Set(val *ProcessExecutionStartResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableProcessExecutionStartResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableProcessExecutionStartResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProcessExecutionStartResponse(val *ProcessExecutionStartResponse) *NullableProcessExecutionStartResponse {
	return &NullableProcessExecutionStartResponse{value: val, isSet: true}
}

func (v NullableProcessExecutionStartResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProcessExecutionStartResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
